// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTDQQjj_xjFAivIDW_-2GWEU4KZCvkbk',
    appId: '1:176133725327:web:3b9621eef0b25549e364fa',
    messagingSenderId: '176133725327',
    projectId: 'serendib-d3b88',
    authDomain: 'serendib-d3b88.firebaseapp.com',
    storageBucket: 'serendib-d3b88.firebasestorage.app',
    measurementId: 'G-CJ147TJ65G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUBW7pGFCxRxkvp5tYsYSuIW0bw8ocT8',
    appId: '1:176133725327:android:ae03a384717aedece364fa',
    messagingSenderId: '176133725327',
    projectId: 'serendib-d3b88',
    storageBucket: 'serendib-d3b88.firebasestorage.app',
  );
}
